### ISSUE TITLE
大佬啊！

### ISSUE THREAD

**Issue by L1cardo** [liuyi12138/HustPingJiao#1]
将近100个老师，要累死了！  谢谢大佬！

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by L1cardo** [comment]
哪天面基，交流一下，哈哈哈

**Comment by liuyi12138** [comment]
哇，有人用真的是受宠若惊嗷

**Comment by L1cardo** [comment]
你的是适用于主校区的，是一个科目只有一个老师的
其实你获取的带有page的url不是真实的url，真实的url都是带科目代码和老师代码的。
我用了你的代码，然后自己稍微修改了一下，适用于同济小区的，可以吧，不行的话就删了
你可以看看，然后看看能不能修改一下  [这里查看](https://github.com/L1cardo/TJMU-Teacher-Evaluation)

**Comment by liuyi12138** [comment]
我觉得主要问题还是url的组成方式，你那边不能一键完成全部评教是因为无法知道有多少个老师吗，写个循环我觉得应该可以解决吧，如果没有这个网页就break掉，或者想办法去获取到老师数目也可以，我这边也没法调试23333。
没想到你们那边真的有这个需求嗷，我就是写着玩玩。
你的代码管理真的好强啊，我还是要学习的嗷

**Comment by liuyi12138** [comment]
可以互相follow一下 嘿嘿嘿

**Comment by L1cardo** [comment]
不用获取老师数目，直接写个循环，循环次数50，反正它评教完了就会退出。最近忙着考试就没研究循环，就把url改了就直接用了。

还有就是评教页面第一页的url和第二页的url是一样的。。。 这个考完试也得获取真实url

我学医，对这个也只是略懂，考完试在研究一下吧，哈哈哈😂

**Comment by L1cardo** [comment]
校园网的评价系统好像出现问题了，评价完每一个老师后，可能网页会刷新还是什么，到时之前获取的数据不能被 Chromedriver 找到，大佬能看看有什么解决办法吗？
评价完第一个老师以后，报错：
`selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document`

**Comment by liuyi12138** [comment]
emmm我也没有测试环境啊，我这都只有1个老师2333，找不到就直接重新打开第二个老师的页面可以吗
